package cmd

func init() {
	workitemSearchCmd.Flags().String("category", "Req", "category")
	workitemSearchCmd.Flags().String("space-id", "", "project/space id")
	workitemSearchCmd.Flags().String("assigned-to", "", "assignee user id or 'self'")
	workitemSearchCmd.Flags().String("creator", "", "creator user id or 'self'")
	workitemSearchCmd.Flags().String("subject", "", "subject contains")
	workitemSearchCmd.Flags().String("status-stage", "", "status stage ids, comma-separated")
	workitemSearchCmd.Flags().String("type", "", "work item type ids, comma-separated")
	workitemSearchCmd.Flags().String("priority", "", "priority ids, comma-separated")
	workitemSearchCmd.Flags().String("order-by", "gmtCreate", "orderBy")
	workitemSearchCmd.Flags().String("sort", "desc", "asc|desc")
	workitemSearchCmd.Flags().Int("page", 1, "page")
	workitemSearchCmd.Flags().Int("per-page", 20, "per page")
	workitemGetCmd.Flags().String("id", "", "work item id or serial (or positional arg)")
	workitemCommentsListCmd.Flags().String("id", "", "work item id (required)")
	workitemCommentsListCmd.Flags().Int("page", 1, "page")
	workitemCommentsListCmd.Flags().Int("per-page", 20, "per page")
	addSortFlag(workitemCommentsListCmd)
	workitemCommentCmd.Flags().String("id", "", "work item id (required)")
	workitemCommentCmd.Flags().String("content", "", "comment content (required)")
	workitemCreateCmd.Flags().String("space-id", "", "project/space id (required)")
	workitemCreateCmd.Flags().String("type-id", "", "work item type id (required)")
	workitemCreateCmd.Flags().String("subject", "", "title (required)")
	workitemCreateCmd.Flags().String("assigned-to", "", "assignee user id or self (required)")
	workitemCreateCmd.Flags().String("description", "", "description")
	workitemCreateCmd.Flags().String("format-type", "", "RICHTEXT|MARKDOWN")
	workitemCreateCmd.Flags().String("parent-id", "", "parent work item id")
	workitemCreateCmd.Flags().String("sprint", "", "sprint id (omit if type has not enabled 迭代)")
	workitemCreateCmd.Flags().String("labels", "", "comma-separated label ids")
	workitemCreateCmd.Flags().String("participants", "", "comma-separated user ids")
	workitemCreateCmd.Flags().String("trackers", "", "comma-separated user ids")
	workitemCreateCmd.Flags().String("verifier", "", "verifier user id or self")
	workitemCreateCmd.Flags().String("versions", "", "comma-separated version ids")
	workitemCreateCmd.Flags().String("custom-fields", "", "JSON object of customFieldValues (fieldId to value)")
	workitemCreateCmd.Flags().Bool("no-defaults", false, "skip profile workitem_defaults for this type")
	workitemUpdateCmd.Flags().String("id", "", "work item id (required)")
	workitemUpdateCmd.Flags().String("subject", "", "new subject")
	workitemUpdateCmd.Flags().String("status", "", "status id")
	workitemUpdateCmd.Flags().String("assigned-to", "", "assignee user id or self")
	workitemUpdateCmd.Flags().String("priority", "", "priority id")
	workitemUpdateCmd.Flags().String("description", "", "description")
	workitemUpdateCmd.Flags().String("labels", "", "comma-separated label ids")
	workitemUpdateCmd.Flags().String("sprint", "", "sprint id")
	workitemUpdateCmd.Flags().String("verifier", "", "verifier user id or self")
	workitemUpdateCmd.Flags().String("participants", "", "comma-separated user ids")
	workitemUpdateCmd.Flags().String("trackers", "", "comma-separated user ids")
	workitemUpdateCmd.Flags().String("versions", "", "comma-separated version ids")
	workitemUpdateCmd.Flags().String("custom-fields", "", "JSON object of custom fields (merged onto body like MCP)")
	workitemUpdateCmd.Flags().String("cancel-reason", "", "set 取消原因 custom field (looked up on item type); useful with --status 已取消/141230")
	workitemRelationsListCmd.Flags().String("id", "", "work item id (required)")
	workitemRelationsListCmd.Flags().String("relation-type", "", "relation type (required); e.g. ASSOCIATED, DEPEND_ON")
	workitemRelationsCreateCmd.Flags().String("id", "", "work item id (required)")
	workitemRelationsCreateCmd.Flags().String("related-id", "", "related work item id (required)")
	workitemRelationsCreateCmd.Flags().String("relation-type", "", "relation type (required); e.g. ASSOCIATED, DEPEND_ON (RELATED/PARENT_SUB often fail)")
	workitemRelationsDeleteCmd.Flags().String("id", "", "work item id (required)")
	workitemRelationsDeleteCmd.Flags().String("related-id", "", "related work item id (required)")
	workitemRelationsDeleteCmd.Flags().String("relation-type", "", "relation type (required); e.g. ASSOCIATED, DEPEND_ON")
	workitemDeleteCmd.Flags().String("id", "", "work item id (required)")
	workitemFieldsCmd.Flags().String("space-id", "", "project/space id (required)")
	workitemFieldsCmd.Flags().String("type-id", "", "work item type id (required)")
	workitemWorkflowCmd.Flags().String("space-id", "", "project/space id (required)")
	workitemWorkflowCmd.Flags().String("type-id", "", "work item type id (required)")
	workitemActivitiesCmd.Flags().String("id", "", "work item id (required)")
	addSortFlag(workitemActivitiesCmd)
	workitemTypesListCmd.Flags().String("space-id", "", "project/space id (required)")
	workitemTypesListCmd.Flags().String("category", "Req", "Req|Task|Bug|Risk|…")
	workitemCommentsCmd.AddCommand(workitemCommentsListCmd)
	workitemAttachmentsListCmd.Flags().String("id", "", "work item id (required)")
	workitemAttachmentsCreateCmd.Flags().String("id", "", "work item id (required)")
	workitemAttachmentsCreateCmd.Flags().String("file", "", "relative file path (required)")
	workitemAttachmentsCreateCmd.Flags().String("file-name", "", "override filename (default basename)")
	workitemAttachmentsCreateCmd.Flags().String("operator-id", "", "operator user id (app token)")
	workitemRelationsCmd.AddCommand(workitemRelationsListCmd, workitemRelationsCreateCmd, workitemRelationsDeleteCmd)
	workitemAttachmentsCmd.AddCommand(workitemAttachmentsListCmd, workitemAttachmentsCreateCmd)
	workitemTypesCmd.AddCommand(workitemTypesListCmd)
	workitemCmd.AddCommand(workitemSearchCmd, workitemGetCmd, workitemCommentsCmd, workitemCommentCmd, workitemCreateCmd, workitemUpdateCmd, workitemDeleteCmd, workitemRelationsCmd, workitemAttachmentsCmd, workitemFieldsCmd, workitemWorkflowCmd, workitemActivitiesCmd, workitemTypesCmd)
}
